language: node_js
node_js:
  - 12

env:
  - SERVICENAME=reverseproxy
  - SERVICENAME=udagram-api-user
  - SERVICENAME=udagram-api-feed
  - SERVICENAME=udagram-frontend

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t $SERVICENAME ./$SERVICENAME
  - docker tag $SERVICENAME charizard117/$SERVICENAME:v1

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io
  - docker push charizard117/SERVICENAME
